document.writeln("<footer>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div class=\'col-md-2 col-sm-3 col-xs-6\'>");
document.writeln("						<h4 class=\'text-center\'>关于我们</h4>");
document.writeln("						<ul>");
document.writeln("							<li><a href=\'#\'>公司简介</a></li>");
document.writeln("							<li><a href=\'#\'>在线留言</a></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-2 col-sm-3 col-xs-6\'>");
document.writeln("						<h4 class=\'text-center\'>产品中心</h4>");
document.writeln("						<ul>");
document.writeln("							<li><a href=\'#\'>果树苗</a></li>");
document.writeln("							<li><a href=\'#\'>绿化苗</a></li>");
document.writeln("							<li><a href=\'#\'>松柏类</a></li>");
document.writeln("							<li><a href=\'#\'>灌木类</a></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-2 col-sm-3 col-xs-6\'>");
document.writeln("						<h4 class=\'text-center\'>基地展示</h4>");
document.writeln("						<ul>");
document.writeln("							<li><a href=\'#\'>樱桃基地展示</a></li>");
document.writeln("							<li><a href=\'#\'>猕猴桃基地展示</a></li>");
document.writeln("							<li><a href=\'#\'>云杉基地展示</a></li>");
document.writeln("							");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-2 col-sm-3 col-xs-6\'>");
document.writeln("						<h4 class=\'text-center\'>新闻中心</h4>");
document.writeln("						<ul>");
document.writeln("							<li><a href=\'#\'>行业资讯</a></li>");
document.writeln("							<li><a href=\'#\'>技术要领</a></li>");
document.writeln("							");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-md-3 col-sm-12 col-xs-12\'>");
document.writeln("						<h2 class=\'text-center\'>全国咨询热线</h2>");
document.writeln("						<span class=\'text-center\' >455-123-13132</span>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</footer>");
document.writeln("		<div class=\'ma\'>");
document.writeln("			<p class=\'text-center\'>CopyRight © 2002-2018 某某苗木绿化有限公司 版权所有</p>");
document.writeln("			<p class=\'text-center\'>ICP备XXXXXXXX号</p>");
document.writeln("		</div>");