document.writeln("<header  class=\'hidden-sm hidden-xs\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'pull-left\'>");
document.writeln("					<img src=\'img/11.png\' class=\'img-responsive\' />");
document.writeln("					<span>全国咨询热线：<em>400-112-1234</em></span>");
document.writeln("				</div>");
document.writeln("				<div class=\'pull-right\'>");
document.writeln("					<ul>");
document.writeln("						<li>");
document.writeln("							<img src=\'img/55.png\' class=\'img-responsive\' />");
document.writeln("							<a href=\'javascript:;\'>一流的服务</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src=\'img/44.png\' class=\'img-responsive\' />");
document.writeln("							<a href=\'javascript:;\'>透明的价格</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src=\'img/33.png\' class=\'img-responsive\' />");
document.writeln("							<a href=\'javascript:;\'>重守信誉</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src=\'img/22.png\' class=\'img-responsive\' />");
document.writeln("							<a href=\'javascript:;\'>优质的苗木</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</header>");
document.writeln("		<nav  class=\'navbar navbar-default nav_top\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("				<div class=\'navbar-header \'>");
document.writeln("				    <button class=\'collapsed navbar-toggle\' type=\'button\' data-toggle = \'collapse\' data-target = \'#bs-example-navbar-collapse-1\'>");
document.writeln("					    <span class=\'icon-bar\'></span>");
document.writeln("					    <span class=\'icon-bar\'></span>");
document.writeln("					    <span class=\'icon-bar\'></span>");
document.writeln("				    </button>");
document.writeln("				    <a class=\'navbar-brand\'><img src=\'img/logo.png\' class=\'img-responsive\' /></a>");
document.writeln("			    </div>");
document.writeln("			");
document.writeln("			    <div class=\'collapse navbar-collapse pull-right\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("				    <ul class=\'nav navbar-nav \' id=\'nav\'>");
document.writeln("					    <li class=\'active wow slideInRight\'><a>网站首页</a></li>");
document.writeln("					    <li class=\'dropdown wow slideInRight\' data-wow-delay = \'.3s\'>");
document.writeln("					    	<a class=\'dropdown-toggle\' data-toggle = \'dropdown\'>关于我们 <span class=\'caret\'></span></a>");
document.writeln("					    	<ul class=\'dropdown-menu\'>");
document.writeln("					    		<li><a href=\'\'>公司简介</a> </li>");
document.writeln("					    		<li><a href=\'\'>在线留言</a> </li>");
document.writeln("					    	</ul>");
document.writeln("					    </li>");
document.writeln("					    <li class=\'dropdown wow slideInRight\'data-wow-delay = \'.6s\'>");
document.writeln("					    	<a class=\'dropdown-toggle\' data-toggle=\'dropdown\'>产品中心 <span class=\'caret\'></span></a>");
document.writeln("					    	<ul class=\'dropdown-menu\'>");
document.writeln("					    		<li><a href=\'\'>果树苗</a> </li>");
document.writeln("					    		<li><a href=\'\'>绿化苗</a> </li>");
document.writeln("					    		<li><a href=\'\'>松柏类</a> </li>");
document.writeln("					    		<li><a href=\'\'>灌木类</a> </li>");
document.writeln("					    	</ul>");
document.writeln("					    </li>");
document.writeln("					    <li class=\'dropdown wow slideInRight\'data-wow-delay = \'.9s\'>");
document.writeln("					    	<a class=\'dropdown-toggle\' data-toggle = \'dropdown\'>基地展示 <span class=\'caret\'></span></a>");
document.writeln("					    	<ul class=\'dropdown-menu\'>");
document.writeln("					    		<li><a href=\'\'>樱桃种植基地</a></li>");
document.writeln("					    		<li><a href=\'\'>猕猴桃种植基地</a></li>");
document.writeln("					    		<li><a href=\'\'>云杉苗种植基地</a></li>");
document.writeln("					    	</ul>");
document.writeln("					    </li>");
document.writeln("					    <li class=\'wow slideInRight\'data-wow-delay = \'1.2s\'><a>资质荣誉</a></li>");
document.writeln("					    <li class=\'dropdown wow slideInRight\'data-wow-delay = \'1.5s\'>");
document.writeln("					    	<a class=\'dropdown-toggle\' data-toggle = \'dropdown\'>新闻中心 <span class=\'caret\'></span></a>");
document.writeln("					    	<ul class=\'dropdown-menu\'>");
document.writeln("					    		<li><a href=\'\'>技术要领</a></li>");
document.writeln("					    		<li><a href=\'\'>行业资讯</a></li>");
document.writeln("					    		");
document.writeln("					    	</ul>");
document.writeln("					    </li>");
document.writeln("					    <li class=\'wow slideInRight\'data-wow-delay = \'1.8s\'><a>联系我们</a></li>");
document.writeln("				    </ul>");
document.writeln("			    </div>");
document.writeln("			    </div>");
document.writeln("			</div>");
document.writeln("		</nav>");